### ISSUE TITLE
Program received signal SIGPIPE, Broken pipe.

### ISSUE THREAD

**Issue by gy741** [naver/arcus-memcached#145]
Hello.

I found a bug.

This issue does not occur every time. 

Thanks.

OS: CentOS 7 64bit
Version: 004342dccee87f15796b1e8365e1f127c25afc4b

```
Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7ffff6472700 (LWP 36514)]
0x00007ffff747fc6d in sendmsg () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff747fc6d in sendmsg () from /lib64/libpthread.so.0
#1  0x000000000041ce24 in transmit (c=0x7ffff00008c8) at memcached.c:14054
#2  conn_mwrite (c=0x7ffff00008c8) at memcached.c:14490
#3  0x000000000040892e in event_handler (fd=<optimized out>, which=<optimized out>, arg=0x7ffff00008c8)
    at memcached.c:14611
#4  0x00007ffff7ba3a14 in event_base_loop () from /lib64/libevent-2.0.so.5
#5  0x000000000042ed29 in worker_libevent (arg=0x690e50) at thread.c:476
#6  0x00007ffff7478e25 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff71a634d in clone () from /lib64/libc.so.6
```

The following processing syntax exists in the original memcached:7623

```
/*
 * ignore SIGPIPE signals; we can use errno == EPIPE if we
 * need that information
 */
    if (sigignore(SIGPIPE) == -1) {
        perror("failed to ignore SIGPIPE; sigaction");
        exit(EX_OSERR);
    }
```

Maybe, SIGPIPE error :

```
Your server process has received a SIGPIPE writing to a socket. 
This usually happens when you write to a socket fully closed on the other (client) side. 
```

**Comment by jhpark816** [comment]
@gy741 

When you debug a program with gdb,
the gdb can grab the SIGPIPE signal
even if the program have ignored the signal.

The gdb handles the SIGPIPE singal accroding to its defined action,
and then forwards it to the process of the program.

You can see the defined action for SIGPIPE with following command in gdb.

```
(gdb) handle SIGPIPE
Signal        Stop	Print	Pass to program	Description
SIGPIPE       Yes	Yes	Yes		Broken pipe
```

If you change like followings, the gdb will not break even if SIGPIPE occurs.

```
(gdb) handle SIGPIPE nostop noprint pass
Signal        Stop	Print	Pass to program	Description
SIGPIPE       No	No	Yes		Broken pipe
```

So, this is not a bug.
It's just a gdb setting issue for signal handle.

Thank you.
